/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monpackage;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Haja
 */
public class AjoutProduitFram extends javax.swing.JFrame {

    /**
     * Creates new form AjoutProduitFram
     */
    private String[][] tableauData;
    private String titre[]  = {"Numero du Produit","Designation" ,"Prix Unitaire","Stock"};
    private int x;
    private Timer tm;
    private String[] Liste2 = {
                "E:\\Backgrounds\\pro1.png",
                "E:\\Backgrounds\\pro2.jpg",
                "E:\\Backgrounds\\pro3.jpg",
                "E:\\Backgrounds\\c3.jpg",
                "E:\\Backgrounds\\c4.jpg",
                "E:\\Backgrounds\\c5.jpg",
                "E:\\Backgrounds\\c6.jpg"
    };
    
      
    public AjoutProduitFram() {
        initComponents();
        changeBack();
    }
    private void changeBack(){
        javax.swing.ImageIcon back = new javax.swing.ImageIcon("E:\\Backgrounds\\pro.jpg");
        java.awt.Image img = back.getImage();
        java.awt.Image imgModif = img.getScaledInstance(panelProd.getWidth(), panelProd.getHeight(), java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon backModif = new javax.swing.ImageIcon(imgModif);
        lblBack.setIcon(backModif);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        panelProd = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Produit = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_numProduit = new javax.swing.JTextField();
        txt_Designation = new javax.swing.JTextField();
        txt_PrixUnitair = new javax.swing.JTextField();
        txt_Stock = new javax.swing.JTextField();
        btn_SuprimerProduit = new javax.swing.JButton();
        btn_ModifierProduit = new javax.swing.JButton();
        btn_AjoutProduit = new javax.swing.JButton();
        lblSlide1 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelProd.setLayout(null);

        table_Produit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {}));
    jScrollPane2.setViewportView(table_Produit);

    panelProd.add(jScrollPane2);
    jScrollPane2.setBounds(110, 10, 452, 236);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 0));
    jLabel1.setText("Numero Produit");
    panelProd.add(jLabel1);
    jLabel1.setBounds(47, 278, 111, 24);

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 0));
    jLabel2.setText("Prix Uniter");
    panelProd.add(jLabel2);
    jLabel2.setBounds(47, 413, 111, 24);

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 0));
    jLabel3.setText("Designation");
    panelProd.add(jLabel3);
    jLabel3.setBounds(47, 347, 111, 24);

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 0));
    jLabel4.setText("Stock");
    panelProd.add(jLabel4);
    jLabel4.setBounds(47, 476, 111, 24);

    txt_numProduit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    txt_numProduit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_numProduitActionPerformed(evt);
        }
    });
    panelProd.add(txt_numProduit);
    txt_numProduit.setBounds(208, 279, 203, 24);

    txt_Designation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    txt_Designation.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_DesignationActionPerformed(evt);
        }
    });
    panelProd.add(txt_Designation);
    txt_Designation.setBounds(208, 347, 203, 24);

    txt_PrixUnitair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    txt_PrixUnitair.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_PrixUnitairActionPerformed(evt);
        }
    });
    txt_PrixUnitair.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txt_PrixUnitairKeyTyped(evt);
        }
    });
    panelProd.add(txt_PrixUnitair);
    txt_PrixUnitair.setBounds(208, 414, 203, 24);

    txt_Stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    txt_Stock.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_StockActionPerformed(evt);
        }
    });
    txt_Stock.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txt_StockKeyTyped(evt);
        }
    });
    panelProd.add(txt_Stock);
    txt_Stock.setBounds(208, 468, 203, 24);

    btn_SuprimerProduit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btn_SuprimerProduit.setText("SUPPRIMER");
    btn_SuprimerProduit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_SuprimerProduitActionPerformed(evt);
        }
    });
    panelProd.add(btn_SuprimerProduit);
    btn_SuprimerProduit.setBounds(440, 390, 159, 33);

    btn_ModifierProduit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btn_ModifierProduit.setText("MODIFIER");
    btn_ModifierProduit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_ModifierProduitActionPerformed(evt);
        }
    });
    panelProd.add(btn_ModifierProduit);
    btn_ModifierProduit.setBounds(440, 460, 159, 33);

    btn_AjoutProduit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btn_AjoutProduit.setText("AJOUTER");
    btn_AjoutProduit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_AjoutProduitActionPerformed(evt);
        }
    });
    panelProd.add(btn_AjoutProduit);
    btn_AjoutProduit.setBounds(440, 320, 159, 33);

    lblSlide1.setBackground(new java.awt.Color(255, 255, 255));
    lblSlide1.setText("jLabel5");
    panelProd.add(lblSlide1);
    lblSlide1.setBounds(614, 314, 343, 214);
    panelProd.add(lblBack);
    lblBack.setBounds(0, 0, 960, 540);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panelProd, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panelProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_numProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numProduitActionPerformed

    private void txt_DesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DesignationActionPerformed

    private void txt_PrixUnitairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PrixUnitairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PrixUnitairActionPerformed

    private void txt_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_StockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_StockActionPerformed

    private void btn_SuprimerProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuprimerProduitActionPerformed
        int[] sup = table_Produit.getSelectedRows();
        String[] numBD; 
        int numLign  = 0;
        Connection con = MyConnection.getconnection();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM produit");
            while(rs.next()){
                numLign = numLign + 1;
            }
            while(rs.previous())
            ;
            numBD = new String[numLign];
           int i = 0;
            while(rs.next()){
                numBD[i] = rs.getString(1);
                i++;
            }
            for(int a:sup){
                st.executeUpdate("DELETE FROM produit WHERE numProduit = '"+numBD[a]+"' ");
                afficher();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AjoutProduitFram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SuprimerProduitActionPerformed

    private void btn_ModifierProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModifierProduitActionPerformed
        ProduitMod pm = new ProduitMod();
        String numpro,des,pu,stock;
        int indice = table_Produit.getSelectedRow();
        numpro = tableauData[indice][0];
        des = tableauData[indice][1];
        pu = tableauData[indice][2];
        stock = tableauData[indice][3];
        pm.setPu(pu);
        pm.setNumPro(numpro);
        pm.setDes(des);
        pm.setStock(stock);
        pm.setNum(numpro);
        jScrollPane2.setViewportView(pm);
        
    }//GEN-LAST:event_btn_ModifierProduitActionPerformed

    private void btn_AjoutProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AjoutProduitActionPerformed
        String num = txt_numProduit.getText();
        String Desi = txt_Designation.getText();
        String Pu = txt_PrixUnitair.getText();
        String Stock = txt_Stock.getText();
        String sqlAjout;
        sqlAjout = "INSERT INTO produit (numProduit, Design, Pu, stock) VALUES('"+num+"', '"+Desi+"',"+Pu+","+Stock+")";
        Connection Con = MyConnection.getconnection();
        
        try {
            Statement st = Con.createStatement();
            st.executeUpdate(sqlAjout);
                    
                    } catch (SQLException ex) {
            Logger.getLogger(AjoutProduitFram.class.getName()).log(Level.SEVERE, null, ex);
        }
        afficher();
    }//GEN-LAST:event_btn_AjoutProduitActionPerformed

    private void txt_PrixUnitairKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PrixUnitairKeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txt_PrixUnitairKeyTyped

    private void txt_StockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_StockKeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txt_StockKeyTyped

    @SuppressWarnings("empty-statement")
    public void afficher(){
        String sqlGet;
        sqlGet = "SELECT * FROM produit";
        Connection Con = MyConnection.getconnection();
        try {
            Statement st = Con.createStatement();
            ResultSet rs = st.executeQuery(sqlGet);
            ResultSetMetaData Data;
            Data = rs.getMetaData();
            int ColNum = Data.getColumnCount();
            int RowNum = 0;   
            int i,j;
                while(rs.next())
                    RowNum++;
                while(rs.previous())
                    ;
                tableauData = new String[RowNum][ColNum];
                i = 0;
                      
                while(rs.next()){
                    j = 0;
                    while(j<ColNum){
                        tableauData [i][j] = rs.getString(j+1); 
                        j++;
                    }
                    i++;
                }  
                table_Produit.setModel(new javax.swing.table.DefaultTableModel(tableauData, titre));
            jScrollPane2.setViewportView(table_Produit);
                } catch (SQLException ex) {
            Logger.getLogger(AjoutProduitFram.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void slider2(){
           modifSlider(6);
            x = 0;
            tm =  new Timer (1000,  new ActionListener(){
                    public void actionPerformed(ActionEvent Ae){
                        modifSlider(x);
                        x = x + 1;
                        if(x>=7)
                            x = 0;
                    }
            });
            
        tm.start();
    }
    public void modifSlider(int i)
    {
        javax.swing.ImageIcon image = new javax.swing.ImageIcon(Liste2[i]);
        java.awt.Image img1 = image.getImage();
        java.awt.Image img2 = img1.getScaledInstance(lblSlide1.getWidth(), lblSlide1.getHeight(), java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon img3 = new javax.swing.ImageIcon(img2);
        lblSlide1.setIcon(img3);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutProduitFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutProduitFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutProduitFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutProduitFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutProduitFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AjoutProduit;
    private javax.swing.JButton btn_ModifierProduit;
    private javax.swing.JButton btn_SuprimerProduit;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblSlide1;
    private javax.swing.JPanel panelProd;
    private javax.swing.JTable table_Produit;
    private javax.swing.JTextField txt_Designation;
    private javax.swing.JTextField txt_PrixUnitair;
    private javax.swing.JTextField txt_Stock;
    private javax.swing.JTextField txt_numProduit;
    // End of variables declaration//GEN-END:variables
}
