/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monpackage;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Haja
 */
public class AjoutCommande extends javax.swing.JFrame {

    /**
     * Creates new form AjoutCommande
     */
    String[][] donnee;
    String[] titres = {"Numero du Client", "Numero produit", "Quantite", "Date"};
    private int x;
    private Timer tm;
    private String[] liste = {
        "E:\\Backgrounds\\c1.png",//0
        "E:\\Backgrounds\\c2.jpg",//1
        "E:\\Backgrounds\\c3.jpg",//2
        "E:\\Backgrounds\\c4.jpg",//3
        "E:\\Backgrounds\\c5.jpg",//4
        "E:\\Backgrounds\\c6.jpg"//5
    };

    public AjoutCommande() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2_Produit = new javax.swing.JComboBox<>();
        jComboBox1_Client = new javax.swing.JComboBox<>();
        txt_quantite = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Commande = new javax.swing.JTable();
        btn_modifier = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        btn_ajout = new javax.swing.JButton();
        lblSlide = new javax.swing.JLabel();
        date_commande = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Numero Client");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Quantite");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Numero Produit");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Date de Commande");

        jComboBox2_Produit.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox2_Produit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2_Produit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2_ProduitActionPerformed(evt);
            }
        });

        jComboBox1_Client.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox1_Client.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_ClientActionPerformed(evt);
            }
        });

        txt_quantite.setBackground(new java.awt.Color(255, 102, 102));
        txt_quantite.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_quantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantiteActionPerformed(evt);
            }
        });

        table_Commande.setBackground(new java.awt.Color(0, 255, 204));
        table_Commande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {}
        ));
        jScrollPane1.setViewportView(table_Commande);

        btn_modifier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_modifier.setText("Modifier");

        btn_supprimer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_ajout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ajout.setText("Ajouter");
        btn_ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_quantite, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox2_Produit, 0, 152, Short.MAX_VALUE)
                        .addComponent(jComboBox1_Client, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(date_commande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(65, 65, 65)))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblSlide, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2_Produit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_supprimer))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_quantite, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_modifier))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(date_commande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(lblSlide, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ajout))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2_ProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2_ProduitActionPerformed

    }//GEN-LAST:event_jComboBox2_ProduitActionPerformed
    public void affiche2() {
        String[] rowNomPro;
        String getSql = "SELECT numProduit From produit";
        Connection Con1 = MyConnection.getconnection();
        try {
            Statement st = Con1.createStatement();
            ResultSet rs = st.executeQuery(getSql);
            int rownum = 0;
            while (rs.next()) {
                rownum++;
            }
            while (rs.previous())
                    ;
            rowNomPro = new String[rownum];
            int i = 0;
            while (rs.next()) {
                rowNomPro[i] = rs.getString(1);
                i++;
            }
            javax.swing.DefaultComboBoxModel<String> cmb1;
            cmb1 = new javax.swing.DefaultComboBoxModel(rowNomPro);
            jComboBox2_Produit.setModel(cmb1);
        } catch (SQLException ex) {
            Logger.getLogger(AjoutCommande.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jComboBox1_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_ClientActionPerformed

    }//GEN-LAST:event_jComboBox1_ClientActionPerformed

    private void txt_quantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantiteActionPerformed

    private void btn_ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajoutActionPerformed
        String numC = jComboBox1_Client.getSelectedItem().toString();
        String numP = jComboBox2_Produit.getSelectedItem().toString();
        String quantite = txt_quantite.getText();
        java.text.SimpleDateFormat sd = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String date = sd.format(date_commande.getDate());
        Connection con = MyConnection.getconnection();
        try {
            Statement st = con.createStatement();
            st.executeUpdate("INSERT INTO commande(numClient, numProduit, qte, date) VALUES('" + numC + "','" + numP + "','" + quantite + "','" + date + "')");
        } catch (SQLException ex) {
            Logger.getLogger(AjoutCommande.class.getName()).log(Level.SEVERE, null, ex);
        }
        afficherTable();
    }//GEN-LAST:event_btn_ajoutActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        int[] sup = table_Commande.getSelectedRows();
        String[] numBD;
        int numLigne = 0;
        Connection con = MyConnection.getconnection();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM commande");
            while (rs.next()) {
                numLigne++;
            }
            while (rs.previous())
                 ;
            numBD = new String[numLigne];

            int i = 0;
            while (rs.next()) {
                numBD[i] = rs.getString(1);
                i++;
            }
            for (int a : sup) {
                st.executeUpdate("DELETE FROM commande WHERE id = '" + numBD[a] + "' ");
            }

        } catch (SQLException ex) {
            Logger.getLogger(AjoutCommande.class.getName()).log(Level.SEVERE, null, ex);
        }
        afficherTable();
    }//GEN-LAST:event_btn_supprimerActionPerformed

    public void afficherTable() {
        int rowNum = 0;
        Connection con = MyConnection.getconnection();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM commande");
            while (rs.next()) {
                rowNum++;
            }
            donnee = new String[rowNum][5];
            while (rs.previous())
                ;
            int i = 0;
            int j;
            java.text.SimpleDateFormat sk = new java.text.SimpleDateFormat("dd MMM yyyy");
            while (rs.next()) {
                j = 0;
                while (j < 5) {
                    donnee[i][j] = (j != 4) ? rs.getString(j + 1) : sk.format(rs.getDate(j + 1));
                    j++;
                }
                i++;
            }
            table_Commande.setModel(new javax.swing.table.DefaultTableModel(donnee, titres));
            jScrollPane1.setViewportView(table_Commande);
        } catch (SQLException ex) {
            Logger.getLogger(AjoutCommande.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void affiche1() {
        String[] rowNom;
        String getsql = "SELECT numClient FROM client";
        Connection con = MyConnection.getconnection();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(getsql);
            int rownum = 0;

            while (rs.next()) {
                rownum++;
            }
            while (rs.previous())
                ;
            rowNom = new String[rownum];
            int i = 0;
            while (rs.next()) {
                rowNom[i] = rs.getString(1);
                i++;
            }
            javax.swing.DefaultComboBoxModel<String> cbm;
            cbm = new javax.swing.DefaultComboBoxModel<>(rowNom);

            jComboBox1_Client.setModel(cbm);

        } catch (SQLException ex) {
            Logger.getLogger(AjoutCommande.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void slide1() {
        modifImage(5);
        x = 0;
        tm = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent ed) {
                modifImage(x);
                x = x + 1;
                if (x >= 6) {
                    x = 0;
                }
            }

        });
        tm.start();
    }

    public void modifImage(int i) {
        javax.swing.ImageIcon image = new javax.swing.ImageIcon(liste[i]);
        java.awt.Image img = image.getImage();
        java.awt.Image img1 = img.getScaledInstance(lblSlide.getWidth(), lblSlide.getHeight(), java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon img2 = new javax.swing.ImageIcon(img1);
        lblSlide.setIcon(img2);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AjoutCommande().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajout;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser date_commande;
    private javax.swing.JComboBox<String> jComboBox1_Client;
    private javax.swing.JComboBox<String> jComboBox2_Produit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSlide;
    private javax.swing.JTable table_Commande;
    private javax.swing.JTextField txt_quantite;
    // End of variables declaration//GEN-END:variables
}
